# libraries :numpy,matplotlib,seaborn,pandas,scipy,scikit-learn(ml)

In [4]:
#numpy :  array 
import numpy as np

In [5]:
arr= np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
l=[1,2,3]
arr = np.array(l)
print(arr)

[1 2 3]


In [10]:
l=[[1,2,3],[4,5,7],[9,7,8]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 7],
       [9, 7, 8]])

In [11]:
# linspace: linear Space
np.linspace(0,10,3) #start,end ,values of number

array([ 0.,  5., 10.])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
#random of numpy
np.random.rand(2)

array([0.99775509, 0.58105418])

In [15]:
np.random.randint(0,100)

18

In [17]:
np.random.randn(5)

array([ 0.46754698,  0.65840974, -1.47331461,  0.05881325, -1.83591515])

In [18]:
np.random.randn(5,5)

array([[-0.3833935 ,  0.96263818, -0.15856994,  0.79919453, -0.36667466],
       [ 1.15792585,  0.75436045,  1.25049346,  0.20982225, -0.71405991],
       [-0.62610862,  1.30454568,  0.1002164 ,  0.35050122, -0.05622793],
       [-0.05600497,  0.66235004,  0.39752654,  0.24146646, -0.36598858],
       [ 1.33484958,  1.20565423, -0.62249096, -0.12137507,  0.03921115]])

In [20]:
np.random.randint(1,100,10)

array([ 9, 28, 33, 47, 62, 42, 12, 79, 64, 77], dtype=int32)

In [27]:
# seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [26]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [28]:
#Reshape
arr=np.arange(0,25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr=arr.reshape(5,5)

In [32]:
arr.shape

(5, 5)

In [45]:
arr=np.arange(0,25)
arr.max()

np.int64(24)

In [38]:
arr.min()

np.int64(0)

In [40]:
arr.argmax() #indexing of max values

np.int64(24)

In [41]:
arr.argmin() # indexing of min values

np.int64(0)

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x=arr.copy()

In [8]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#2d  slicing 
l=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(l)

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr[1][2]

np.int64(6)

In [13]:
arr[0:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [17]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [22]:
# array with array function
arr1= np.arange(0,10)
arr2 = np.arange(11,21)
arr1 + arr2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [24]:
 # universal  array function
arr =np.arange(0,10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
# trignometric
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [28]:
np.log(10)

np.float64(2.302585092994046)

In [29]:
l=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(l)

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.sum(axis=0) # add values  (vertical) in row 

array([12, 15, 18])

In [32]:
arr.sum(axis=1) # add values (horizontal) in coloumn

array([ 6, 15, 24])

In [5]:
import numpy as np
np.arange(1,6)

array([1, 2, 3, 4, 5])

# Series 

In [1]:
import numpy as np
import pandas as pd

In [2]:
nameuser=['USA','INDIA','CANADA']
nameindex =[112,113,114]

In [3]:
ages ={'Sammy':5,'Frank':10,'Spike':7}

In [4]:
ages

{'Sammy': 5, 'Frank': 10, 'Spike': 7}

In [5]:
pd.Series(ages)

Sammy     5
Frank    10
Spike     7
dtype: int64

In [7]:
expense=pd.Series({"bobs":3660,"vishal":3645,"vikram":3467})
res= expense['bobs']
res

np.int64(3660)

In [8]:
q1={"japan":300, "china":320,"india":380 ,"usa":82}
q2 ={"brazil":463,"china":563,"india":89,"usa":68}

In [9]:
sales_q1=pd.Series(q1)
sales_q2=pd.Series(q2)

In [10]:
sales_q1[0]

C:\Users\karmv\AppData\Local\Temp\ipykernel_16744\92651501.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_q1[0]


np.int64(300)

In [1]:
#pandas: library : collection of function :manipulation of data
#basic data type: Series (array/list but it contains 2 elements: index, data, dictionary:key,value)

In [2]:
import pandas as pd 
my_data =[1,2,3,4]
my_index=["aman","ram","vikas","prakash"]
ser1= pd.Series(data= my_data,index=my_index)
ser1

aman       1
ram        2
vikas      3
prakash    4
dtype: int64

In [3]:
ser2=pd.Series(data=my_data)
ser2

0    1
1    2
2    3
3    4
dtype: int64

In [2]:
#Series : Collection index, data
#pandas :DataFrame: Collection of Series with common indexing
import numpy as np
import pandas as pd

In [3]:
mydata=np.arange(1,101).reshape(10,10)
mydata

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [4]:
myindex=["Aman","raman","vijay","ram","vikram","prakash","pik","vik","dei","dhar"]
mycolumn=["jan","frb","mar","apr","may","jun","jul","aug","sep","oct"]

In [5]:
df=pd.DataFrame(data=mydata)
df

0   1   2   3   4   5   6   7   8    9
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100

In [6]:
df=pd.DataFrame(data=mydata,index=myindex)
df

0   1   2   3   4   5   6   7   8    9
Aman      1   2   3   4   5   6   7   8   9   10
raman    11  12  13  14  15  16  17  18  19   20
vijay    21  22  23  24  25  26  27  28  29   30
ram      31  32  33  34  35  36  37  38  39   40
vikram   41  42  43  44  45  46  47  48  49   50
prakash  51  52  53  54  55  56  57  58  59   60
pik      61  62  63  64  65  66  67  68  69   70
vik      71  72  73  74  75  76  77  78  79   80
dei      81  82  83  84  85  86  87  88  89   90
dhar     91  92  93  94  95  96  97  98  99  100

In [7]:
df=pd.DataFrame(data=mydata,index=myindex,columns=mycolumn)
df

jan  frb  mar  apr  may  jun  jul  aug  sep  oct
Aman       1    2    3    4    5    6    7    8    9   10
raman     11   12   13   14   15   16   17   18   19   20
vijay     21   22   23   24   25   26   27   28   29   30
ram       31   32   33   34   35   36   37   38   39   40
vikram    41   42   43   44   45   46   47   48   49   50
prakash   51   52   53   54   55   56   57   58   59   60
pik       61   62   63   64   65   66   67   68   69   70
vik       71   72   73   74   75   76   77   78   79   80
dei       81   82   83   84   85   86   87   88   89   90
dhar      91   92   93   94   95   96   97   98   99  100

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Aman to dhar
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   jan     10 non-null     int64
 1   frb     10 non-null     int64
 2   mar     10 non-null     int64
 3   apr     10 non-null     int64
 4   may     10 non-null     int64
 5   jun     10 non-null     int64
 6   jul     10 non-null     int64
 7   aug     10 non-null     int64
 8   sep     10 non-null     int64
 9   oct     10 non-null     int64
dtypes: int64(10)
memory usage: 880.0+ bytes


In [9]:
df.isnull().sum()

jan    0
frb    0
mar    0
apr    0
may    0
jun    0
jul    0
aug    0
sep    0
oct    0
dtype: int64

In [10]:
#reading  excel/csv :DataFrame
df=pd.read_csv("example.csv")
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [11]:
ls

 Volume in drive C is Windows
 Volume Serial Number is C8AA-8222

 Directory of C:\Users\karmv\OneDrive\Desktop\python Data Analytic File

11-12-2025  19:25    <DIR>          .
24-10-2025  20:04    <DIR>          ..
09-07-2025  16:44    <DIR>          .idea
04-12-2025  18:49    <DIR>          .ipynb_checkpoints
02-08-2025  20:57    <DIR>          __pycache__
04-12-2025  19:28            21,205 03-NumPy-Exercises.ipynb
18-08-2025  14:52           171,509 cleanedsenti.csv
06-08-2025  14:42    <DIR>          data
09-07-2025  12:42    <DIR>          Data Analytic
23-08-2025  10:46    <DIR>          data2
11-12-2025  18:15                51 example.csv
11-12-2025  18:15             5,022 example.xlsx
02-08-2025  21:50           176,421 Exploratory Data Analysis.ipynb
18-08-2025  14:54           171,521 final_cleaned.csv
02-12-2025  18:28            45,962 Function.ipynb
02-08-2025  19:34             3,570 get_vendor_summary.py
11-12-2025  18:16        25,112,317 hotel_booking_data.csv
02-08

In [12]:
df=pd.read_csv("tips.csv")
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [13]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [14]:
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [15]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [16]:
df.tail()

total_bill   tip     sex smoker   day    time  size  price_per_person  \
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
239    Michael Avila  5296068606052842    Sat2657  
240   Monica Sanders  3506806155565404    Sat1766  
241       Keith Wong  6011891618747196    Sat3880  
242     Dennis Dixon     4375220550950      Sat17  
243  Michelle Hardin  3511451626698139    Thur672

In [17]:
df.describe().transpose()

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

In [18]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [19]:
#grab any column
df['total_bill'] #Series

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [20]:
type(df['total_bill'])

pandas.core.series.Series

In [21]:
df[['total_bill','tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [22]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [23]:
df.set_index('Payment ID')

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  
Thur672                 9.39     Michelle Hardin  3511451626698139  

[244 rows x 10 columns]

In [24]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [25]:
df=df.set_index('Payment ID')

In [26]:
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221

In [27]:
df=df.reset_index()

In [28]:
df.head()

Payment ID  total_bill   tip     sex smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2   
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3   
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3   
3    Sun5260       23.68  3.31    Male     No  Sun  Dinner     2   
4    Sun2251       24.59  3.61  Female     No  Sun  Dinner     4   

   price_per_person          Payer Name         CC Number  
0              8.49  Christy Cunningham  3560325168603410  
1              3.45      Douglas Tucker  4478071379779230  
2              7.00      Travis Walters  6011812112971322  
3             11.84    Nathaniel Harris  4676137647685994  
4              6.15        Tonya Carter  4832732618637221

In [30]:
df.iloc[0] #integer based location check

Payment ID                     Sun2959
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: 0, dtype: object

In [32]:
df=df.set_index('Payment ID')

In [33]:
df

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  
Thur672                 9.39     Michelle Hardin  3511451626698139  

[244 rows x 10 columns]

In [34]:
df.loc['Sun2959'] #name based location check 

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [35]:
df.loc[['Sun2959','Sun5260']]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun5260                11.84    Nathaniel Harris  4676137647685994